# @package _global_
hydra:
  run:
    dir: ${BASE_DIR}/outputs/RadialBNNMNISTMissing7/${now:%Y-%m-%d-%H-%M-%S}-${id}/
hoover:
  save_data: false
dataset:
  test_proportion: 0.96
  n_points: 62500
  standardize: true
  name: MNISTDataset
  stratify: true
  respect_train_test: false
  remove_initial_75_keep_train_size: true
  filter_nums:
  - 7
  filter_nums_relative_frequency: 1
  with_unseen: true
experiment:
  n_runs: 1000
  random_seed: -1
  debug: false
  save_data_until: 10
  loss: CrossEntropyLoss
  log_every: 1
  save_every: 1
  abort_test_after: 5000
  constant_val_set: false
risk_estimators:
- TrueRiskEstimator: null
- BiasedRiskEstimator: null
- FancyUnbiasedRiskEstimator: null
- QuadratureRiskEstimator: null
- ConvexComboWithOutUncertainty: null
- FullSurrogateASMC: null
- FullSurrogateASMC: Limit50p
- FullSurrogateASMC: Limit10p
acquisition_functions:
- RandomAcquisition: NoSave
- ClassifierAcquisitionEntropy: NoSave
- SelfSurrogateAcquisitionEntropy: Surr
- SelfSurrogateAcquisitionSurrogateEntropy: Surr
- SelfSurrogateAcquisitionSurrogateEntropy: SurrNoSample
- SelfSurrogateAcquisitionSurrogateEntropyPlusExpectedLoss: Surr
- SelfSurrogateAcquisitionSurrogateEntropyPlusExpectedLoss: SurrNoSample
acquisition:
  sample: true
  animate: false
  animate_until: 1
  lazy_save: true
  uniform_clip: false
  uniform_clip_val: 0.2
  lazy_save_schedule:
  - 0
id: 0
model:
  name: RadialBNN
  channels: 16
  skip_fit_debug: false
  data_CHW:
  - 1
  - 28
  - 28
  lazy: true
  efficient: true
  calibrated: true
  load_calibration: false
  training_cfg:
    validation_set_size: 500
    stratify_val: true
    max_epochs: 500
    learning_rate: 0.0001
    batch_size: 64
    variational_samples: 8
    num_workers: 4
    pin_memory: true
    early_stopping_epochs: 10
    padding_epochs: none
    num_repetitions: 1
    weight_decay: 0.0001
    model: radial_bnn
    channels: 16
    checkpoints_frequency: 3
    data_noise_proportion: None
  testing_cfg:
    variational_samples: 100
risk_configs:
  Limit50p:
    limit: 0.5
  Limit10p:
    limit: 0.1
acquisition_configs:
  NoSave:
    acquisition:
      animate: false
  Surr:
    name: RadialBNN
    channels: 16
    skip_fit_debug: false
    save_path: single_aux/model.pth
    data_CHW:
    - 1
    - 28
    - 28
    lazy: true
    lazy_schedule:
    - 0
    - 5
    - 10
    - 20
    - 30
    - 40
    - 50
    - 70
    - 100
    - 125
    - 150
    - 200
    - 250
    - 300
    - 350
    - 400
    - 450
    - 500
    - 550
    - 600
    - 650
    - 700
    - 750
    - 800
    - 850
    - 900
    - 950
    - 1000
    - 1250
    - 1500
    - 1750
    - 2000
    - 2500
    - 3000
    - 3500
    - 4000
    - 4500
    - 4900
    efficient: true
    calibrated: true
    load_calibration: false
    temp_save_path: single_aux/temperature.json
    val_idxs: false
    training_cfg:
      validation_set_size: 500
      stratify_val: true
      max_epochs: 500
      learning_rate: 0.0001
      batch_size: 64
      variational_samples: 8
      num_workers: 4
      pin_memory: true
      early_stopping_epochs: 10
      padding_epochs: none
      num_repetitions: 1
      weight_decay: 0.0001
      model: radial_bnn
      channels: 16
      checkpoints_frequency: 3
      data_noise_proportion: None
    testing_cfg:
      variational_samples: 100
  SurrNoSample:
    acquisition:
      sample: false
    name: RadialBNN
    channels: 16
    skip_fit_debug: false
    save_path: single_aux/model.pth
    data_CHW:
    - 1
    - 28
    - 28
    lazy: true
    lazy_schedule:
    - 0
    - 5
    - 10
    - 20
    - 30
    - 40
    - 50
    - 70
    - 100
    - 125
    - 150
    - 200
    - 250
    - 300
    - 350
    - 400
    - 450
    - 500
    - 550
    - 600
    - 650
    - 700
    - 750
    - 800
    - 850
    - 900
    - 950
    - 1000
    - 1250
    - 1500
    - 1750
    - 2000
    - 2500
    - 3000
    - 3500
    - 4000
    - 4500
    - 4900
    efficient: true
    calibrated: true
    load_calibration: false
    temp_save_path: single_aux/temperature.json
    val_idxs: false
    training_cfg:
      validation_set_size: 500
      stratify_val: true
      max_epochs: 500
      learning_rate: 0.0001
      batch_size: 64
      variational_samples: 8
      num_workers: 4
      pin_memory: true
      early_stopping_epochs: 10
      padding_epochs: none
      num_repetitions: 1
      weight_decay: 0.0001
      model: radial_bnn
      channels: 16
      checkpoints_frequency: 3
      data_noise_proportion: None
    testing_cfg:
      variational_samples: 100
  LazySurr:
    name: RadialBNN
    channels: 16
    skip_fit_debug: false
    save_path: single_aux_lazy/model.pth
    data_CHW:
    - 1
    - 28
    - 28
    lazy: true
    lazy_schedule: []
    efficient: true
    calibrated: true
    load_calibration: false
    temp_save_path: single_aux_lazy/temperature.json
    val_idxs: false
    training_cfg:
      validation_set_size: 500
      stratify_val: true
      max_epochs: 500
      learning_rate: 0.0001
      batch_size: 64
      variational_samples: 8
      num_workers: 4
      pin_memory: true
      early_stopping_epochs: 10
      padding_epochs: none
      num_repetitions: 1
      weight_decay: 0.0001
      model: radial_bnn
      channels: 16
      checkpoints_frequency: 3
      data_noise_proportion: None
    testing_cfg:
      variational_samples: 100
